{% set name = "peppy" %}
{% set version = "0.31.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 834c0581023196abe96956b76039b5729594e6b263977fc06b0746ca1323b30b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - attmap >=0.12.5
    - python
    - pyyaml >=5
    - ubiquerg >=0.5.2
    - pandas >=0.24.2
    - logmuse >=0.2

test:
  imports:
    - peppy

about:
  home: https://github.com/pepkit/peppy/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Project metadata manager for PEPs in Python

extra:
  recipe-maintainers:
    - stolarczyk
